# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(703, 510)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 400, 461, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textInput = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textInput.setObjectName("textInput")
        self.horizontalLayout.addWidget(self.textInput)
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendButton.setEnabled(True)
        self.sendButton.setDefault(False)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.connectButton = QtWidgets.QPushButton(Dialog)
        self.connectButton.setGeometry(QtCore.QRect(500, 80, 161, 51))
        self.connectButton.setObjectName("connectButton")
        self.listenButton = QtWidgets.QPushButton(Dialog)
        self.listenButton.setGeometry(QtCore.QRect(500, 140, 161, 51))
        self.listenButton.setObjectName("listenButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(500, 200, 160, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.portLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout_2.addWidget(self.portLabel)
        self.portInput = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.portInput.setObjectName("portInput")
        self.horizontalLayout_2.addWidget(self.portInput)
        self.myPortLabel = QtWidgets.QLabel(Dialog)
        self.myPortLabel.setGeometry(QtCore.QRect(510, 40, 47, 13))
        self.myPortLabel.setObjectName("myPortLabel")
        self.myPortNumber = QtWidgets.QLabel(Dialog)
        self.myPortNumber.setGeometry(QtCore.QRect(560, 40, 47, 13))
        self.myPortNumber.setObjectName("myPortNumber")
        self.chatBox = QtWidgets.QLabel(Dialog)
        self.chatBox.setGeometry(QtCore.QRect(40, 40, 441, 341))
        self.chatBox.setAutoFillBackground(True)
        self.chatBox.setFrameShape(QtWidgets.QFrame.Box)
        self.chatBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.chatBox.setObjectName("chatBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.listenButton.setText(_translate("Dialog", "Listen"))
        self.portLabel.setText(_translate("Dialog", "Port:"))
        self.myPortLabel.setText(_translate("Dialog", "My Port:"))
        self.myPortNumber.setText(_translate("Dialog", "0000"))
        self.chatBox.setText(_translate("Dialog", "TextLabel"))
